[package]
name = "yew-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = "0.11.0"  # 输出日志到控制台
serde = "1.0.217"
serde_json = "1.0.134"
stylist = { version = "0.10.0", features = ["yew"]}  # css 样式宏
yew = "0.19.3"
